### ISSUE TITLE
"type" missing for nodes in Schema

### ISSUE THREAD

**Issue by snmvaughan** [jsongraph/json-graph-specification#25]
The provided examples have a "type" on each node, but this is missing from the JSON Schema.

**Comment by abargnesi** [comment]
I think this is an error in the readme. The JSON files in the *examples* directory do not have a node type (these are validated against the schema using Travis).

We welcome pull requests if you're interested, but thanks for the heads up.

**Comment by ArSn** [comment]
I just stumbled upon this too and saw it is not yet fixed. I am happy to create a pull request either way (currently working on a full fletched JGF client for my web project), but I'd love to know what you think is the right way before that.

As stated my @snmvaughan already, the readme specifies there shall be a type on the node, and personally I think that would make much sense since everything else has a type as well (even though the type of the edge is called "relation" for semantic reasons). I looked at the examples and I think a type for all nodes can be very clearly deducted.

@abargnesi what do you think? If we are worried about breaking changes we could introduce that as optional property.

**Comment by wshayes** [comment]
Sorry to have left this outstanding so long. The type property was removed from the README. We recommend using the metadata field for capturing that. We're trying to keep the required properties limited, but we are happy to provide a list of recommended (but optional) metadata properties in the README and in the JSON Schema.

**Comment by ArSn** [comment]
@wshayes alright, that makes sense, thank you. I saw you closed some other issues yesterday as well.

As a matter of fact I'd like to contribute a bit more to this project because I think it is really great. Since you have no CONTRIBUTING file, can you shed some light on how I should go about that? I.e. should I just suggest solutions to open issues in forms of pull requests? Thanks!

**Comment by wshayes** [comment]
Hi Kolja,

Feel free to PR some contributing guidelines. I prefer the workflow - submit an issue, get feedback, then propose a PR (for anything that is a significant effort - something simple/quick, just propose a PR.

Anselmo and I are the most active - with me taking point now - the Bargnesi brothers seem to have moved on. I'd welcome more contributors/help and after seeing how it goes welcoming you as a member of the team.

More perspectives would be great to have on the project.

**Comment by wshayes** [comment]
@ArSn Ping me at william dot s dot hayes at gmail dot com and we can setup a Zoom conference to discuss ideas for moving JGF forward. Cheers!

**Comment by abargnesi** [comment]
I am not actively using JGF at the moment, but I am interested in participating in a design, theoretical sense.

A `type` node property is useful, but I can't seem to find why I removed it in 817b752963a00b5f0ea06fafcb3f7706707a4bc9. I do remember a discussion with @adifabio about this.

I would vote the existing spec be officially decreed 1.0 and proposals be made for a backwards-compatible 1.1 version.

**Comment by ArSn** [comment]
@wshayes thanks, will do!

Furthermore, I second the proposal of @abargnesi to make a backards-compatible 1.1 version and I too think it makes sense to have a type on the node (it would help in the project I am working on).
