### ISSUE TITLE
Refer to Graph Modelling Language and related formats

### ISSUE THREAD

**Issue by nichtich** [jsongraph/json-graph-specification#36]
The README should at least mention [Graph Modelling Language](https://en.wikipedia.org/wiki/Graph_Modelling_Language) (GML). There is also [a npm package](https://www.npmjs.com/package/jgf2gml) to convert from JGF to GML. It may also make sense to mention other graph formats such as TGF, GraphML etc. and link to converters where available, e.g. https://www.npmjs.com/package/jgf-dot.

**Comment by RangerMauve** [comment]
Yeah, that's a great idea! :D

Would you be interested in submitting a PR for that?

Might be useful to add a "Other formats" section after the [clients section](https://github.com/jsongraph/json-graph-specification#clients)

**Comment by nichtich** [comment]
Ok, I'll summarize what I found so far

**Comment by nichtich** [comment]
See https://github.com/jsongraph/json-graph-specification/pull/37. I did not including references to additional tools, could you merge https://github.com/jsongraph/json-graph-specification/pull/35 first?

**Comment by nichtich** [comment]
I've further extended the list with https://github.com/jsongraph/json-graph-specification/pull/38 but don't intend to dig deeper so you can close this issue. By the way I welcome all standardization but JGF looks a lot like [yet another standard](https://xkcd.com/927/). In the end support in applications is the most relevant factor. Without import and export in most common graph utilities, the standard is useless.

**Comment by wshayes** [comment]
It's fully supported by Cytoscape via the JGF app and it's also a primary format for BioDati Studio.  We created it as it's easy to work with and separates styling from structure. Trying to work with XGMML was painful and didn't support metadata. The Cytoscape CX format is more open for metadata, but I find it really hard to work with. The Cytoscape JS format is mostly focused on presentation rather than structure. I understand about too many standards. We tried really hard to use one that was already out there, but we couldn't find one that fit our needs.
